version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "auto"
    allow:
      dependency-type: "all"
      node-version: "16.x"
