extends: 
  - stylelint-config-standard

ignoreFiles:
  - dist/**/*.css

overrides:
  - files:
    - src/**/*.less
    customSyntax: postcss-less

rules:
  selector-id-pattern: null
  selector-class-pattern: null
  no-descending-specificity: null
  number-max-precision: null
  selector-no-vendor-prefix: null
  value-no-vendor-prefix: null
  at-rule-no-vendor-prefix: null
  media-feature-name-no-vendor-prefix: null
  property-no-vendor-prefix: null
  selector-attribute-quotes: null
  function-no-unknown:
    - true
    - ignoreFunctions:
      - alpha
  comment-empty-line-before: null
  selector-type-no-unknown:
    - true
    - ignoreTypes:
      - ogvjs
  no-duplicate-selectors: null
  declaration-property-value-no-unknown: true