import { type Indicators } from '../../../src/types';

interface IconItem {
  title: string;
  icons: string[];
}

/** 支持的图标列表 */
export const iconList: IconItem[] = [
  {
    title: 'Icons – movement',
    icons: [
      // 'arrowDown',
      'arrowNext',
      'arrowPrevious',
      // 'arrowUp',
      'collapse',
      'downTriangle',
      'draggable',
      'doubleChevronEnd',
      'doubleChevronStart',
      'expand',
      'move',
      'first',
      'last',
      'next',
      'previous',
      'sortVertical',
      'upTriangle',
    ],
  },
  {
    title: 'Icons – content',
    icons: [
      'article',
      'articles',
      'articleAdd',
      'articleCheck',
      'articleDisambiguation',
      'articleNotFound',
      'articleNotFound (he, yi)',
      'articleSearch',
      'articlesSearch',
      'articleRedirect',
      'database',
      'die',
      'download',
      'folderPlaceholder',
      'history',
      'info',
      'info (ar)',
      'infoFilled',
      'infoFilled (ar)',
      'qrCode',
      'robot',
      'share',
      'specialPages',
      'tag',
      'upload',
      'window',
    ],
  },
  {
    title: 'Icons – alerts',
    icons: [
      'alert',
      'bell',
      'bellOutline',
      'error',
      'message',
      'notice',
      'speechBubble',
      'speechBubbleAdd',
      'speechBubbles',
      'success',
      'tray',
    ],
  },
  {
    title: 'Icons – interactions',
    icons: [
      'add',
      'browser',
      'cancel',
      'check',
      'checkAll',
      'clear',
      'clock',
      'close',
      'ellipsis',
      'verticalEllipsis',
      'feedback',
      'funnel',
      'hand',
      'heart',
      'help',
      'help (he, yi)',
      'helpNotice',
      'helpNotice (he, yi)',
      'home',
      'key',
      'keyboard',
      'lightbulb',
      'logIn',
      'logOut',
      'network',
      'networkOff',
      'newWindow',
      'pageSettings',
      // 'power',
      'printer',
      'reload',
      'search',
      'settings',
      'subtract',
    ],
  },
  {
    title: 'Icons – moderation',
    icons: [
      'bookmarkOutline',
      'bookmark',
      'block',
      'unBlock',
      'flag',
      'unFlag',
      'lock',
      'unLock',
      'restore',
      'star',
      'halfStar',
      'unStar',
      'trash',
      'pushPin',
      'ongoingConversation',
    ],
  },
  {
    title: 'Icons – editing-core',
    icons: [
      'edit',
      'editLock',
      'editUndo',
      'link',
      'unLink',
      'linkExternal',
      'linkSecure',
      'redo',
      'undo',
    ],
  },
  {
    title: 'Icons – editing-styling',
    icons: [
      'bigger',
      'smaller',
      'subscript',
      'superscript',
      'bold',
      'bold (ar)',
      'bold (az)',
      'bold (be)',
      'bold (ce)',
      'bold (cs, en, he, ml, pl, sco)',
      'bold (da, de, hu, ksh, nb, nn, no, sv)',
      'bold (es, gl, pt)',
      'bold (eu, fi)',
      'bold (fa)',
      'bold (fr, it)',
      'bold (hy)',
      'bold (ka)',
      'bold (ky, ru, uk)',
      'bold (nl)',
      'bold (os)',
      'bold (ur)',
      'highlight',
      'italic',
      'italic (ar)',
      'italic (cs, en, fr, he, ml, pl, pt, sco)',
      'italic (az, be, ce, da, de, fi, ky, nb, nn, no, os, sv, ru, uk)',
      'italic (es, gl, it, nl)',
      'italic (eu)',
      'italic (fa)',
      'italic (hu)',
      'italic (hy)',
      'italic (ksh)',
      'italic (ka)',
      'italic (ur)',
      'strikethrough',
      'strikethrough (en, nb, nn, no)',
      'strikethrough (fi)',
      'underline',
      'underline (en, de, nb, nn, no, sv)',
      'textLanguage',
      'textDirLTR',
      'textDirRTL',
      'textStyle',
    ],
  },
  {
    title: 'Icons – editing-functions',
    icons: [
      'function',
      'functionArgument',
      'instance',
      'literal',
    ],
  },
  {
    title: 'Icons – editing-list',
    icons: [
      'indent',
      'listBullet',
      'listNumbered',
      'outdent',
    ],
  },
  {
    title: 'Icons – editing-advanced',
    icons: [
      'alignCenter',
      'alignLeft',
      'alignRight',
      'attachment',
      'calendar',
      'code',
      'copy',
      'cut',
      'hieroglyph',
      'imageLayoutBasic',
      'imageLayoutFrame',
      'imageLayoutFrameless',
      'imageLayoutThumbnail',
      'labFlask',
      'language',
      'layout',
      'markup',
      'mathematics',
      'mathematicsDisplayBlock',
      'mathematicsDisplayDefault',
      'mathematicsDisplayInline',
      'newline',
      'noWikiText',
      'ocr',
      'outline',
      'palette',
      'paste',
      'puzzle',
      'quotes',
      'sandbox',
      'searchCaseSensitive',
      'searchDiacritics',
      'searchRegularExpression',
      'signature',
      'specialCharacter',
      'table',
      'tableAddColumnAfter',
      'tableAddColumnBefore',
      'tableAddRowAfter',
      'tableAddRowBefore',
      'tableCaption',
      'tableMergeCells',
      'tableMoveColumnAfter',
      'tableMoveColumnBefore',
      'tableMoveRowAfter',
      'tableMoveRowBefore',
      'templateAdd',
      'translation',
      'wikiText',
    ],
  },
  {
    title: 'Icons – editing-citation',
    icons: [
      'book',
      'journal',
      'newspaper',
      'reference',
      'referenceExisting',
      'references',
    ],
  },
  {
    title: 'Icons – media',
    icons: [
      'camera',
      'chart',
      'exitFullscreen',
      'fullScreen',
      'image',
      'imageAdd',
      'imageBroken',
      'imageLock',
      'imageGallery',
      'musicalScore',
      'pause',
      'play',
      'stop',
      'volumeDown',
      'volumeOff',
      'volumeUp',
      'zoomIn',
      'zoomOut',
    ],
  },
  {
    title: 'Icons – location',
    icons: [
      'globe',
      'map',
      'mapPin',
      'mapPinAdd',
      'mapTrail',
    ],
  },
  {
    title: 'Icons – user',
    icons: [
      'userAdd',
      'userAnonymous',
      'userAvatar',
      'userAvatarOutline',
      'userContributions',
      'userGroup',
      'userRights',
      'userTalk',
      'userTemporary',
      // 'userTemporaryLocation',
      'watchlist',
    ],
  },
  {
    title: 'Icons – layout',
    icons: [
      'menu',
      'recentChanges',
      'textFlow',
      'textSummary',
      'viewCompact',
      'viewDetails',
    ],
  },
  {
    title: 'Icons – accessibility',
    icons: [
      'appearance',
      'bright',
      'halfBright',
      'notBright',
      'eye',
      'eyeClosed',
      'moon',
      'largerText',
      'smallerText',
      'visionSimulator',
    ],
  },
  {
    title: 'Icons – wikimedia',
    icons: [
      'logoCC',
      // 'logoCodex',
      'logoMediaWiki',
      'logoMetaWiki',
      'logoWikibooks',
      'logoWikidata',
      'logoWikifunctions',
      'logoWikimedia',
      'logoWikimediaCommons',
      'logoWikimediaDiscovery',
      'logoWikinews',
      'logoWikipedia',
      'logoWikiquote',
      'logoWikisource',
      'logoWikispecies',
      'logoWikiversity',
      'logoWikivoyage',
      'logoWiktionary',
    ],
  },
];

export const indicatorList: Indicators[] = [
  'clear', 'up', 'down', 'required',
];
